spring.datasource.url=jdbc:postgresql://dbv1_z88c_user:M4nhSvGp8SMPYnP8uAJwtkMnmvFxuSE2@dpg-d7llg98g4nts73d2h9mg-a.frankfurt-postgres.render.com/dbv1_z88c
spring.datasource.username=dbv1_z88c_user
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000