spring.datasource.url=jdbc:postgresql://localhost:5332/dbv1
spring.datasource.username=dbv1
spring.datasource.password=pass123

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
app.jwt.secret=ThisIsAVeryLongSecretKeyForCoreBankingAppThatIsAtLeast256Bits!
# In seconds
app.jwt.expiration=86400000